---
 - name: install firewall on host scope variables
   hosts: webserver
   tasks: 
      - name: install firewall
        apt:
          name: "{{a}}"
          state: "{{b}}"
          update_cache: "{{c}}"
...
