---
 - name: impenenting tags
   hosts: all
   gather_facts: false
   become: yes
   tasks:
      - name: install tree
        apt:
          name: tree
          state: present
          update_cache: yes
        tags: tree_installation
      - name: create user
        user: 
          name: sham
          password: sham
        tags: user_creation
      - name: copy the passwd file
        copy:
           src: /etc/passwd
           dest: /tmp
...
